

function setup() {

	// WEBGL is used to make 3d things
	createCanvas(600,600, WEBGL);
	angleMode(DEGREES);

}

function draw() {

	background(30, 33, 82);

	//rotates the circles that are generated by 50 degrees
	rotateX(60);

	noFill();
	strokeWeight(3);
	stroke(85, 91, 181);

	//this for loop determines the amount of circles that are generated
	for (var i = 0; i < 20; i++) {

		//beginShape is used to make custom shapes, in this case ellipses
		beginShape()

		//this for loop repeats to place each of the points(verticies) to create one ellipse
		for (var j = 0; j < 360; j += 10) {

			//makes a variable which determines the radius of the ellipse, based on i which is the number of circles
			var rad = i * 12;
			//this creates an x variable to place the vertex, uses the radius value determined above, multiplied by cos(j) 
			//using sin/cos is what helps make the movement less rigid and more 'lifelike' bc when multiplied it creates a curve/wave (oscillating effect)
			var x = rad * cos(j);
			//same but for the y coord
			var y = rad * sin(j);
			//this determines the z coord
			//framecount helps it run at the right speed, this can be multiplied to adjust it but i found the default was the right speed
			//the i is from the variable of the outer loop, itss what makes each circle move slightly differently and can be intensified by multiplying it by a higher value
			//the final value that its multiplied by (60) affects how drastic the movements are along the z axis (how high/low)
			var z = sin(frameCount + i * 1.5) * 60;

		//uses the variables to make the vertex
		vertex(x,y,z);

		}
		//ends the shape once the inner for loop is over, then the outer loop restarts
		endShape(CLOSE);

	}

}